apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: cy8lvq3jd-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: cy8lvq3jd-go 
  name: cy8lvq3jd-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: cy8lvq3jd-go 
